# Generated by Django 3.2.13 on 2022-06-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_bloodbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='confirm',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
